---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5

suites:
  - name: client
    run_list:
      - recipe[puppet::client]
    attributes:
      puppet:
        client_conf:
          main:
            server: 'ec2-54-82-223-163.compute-1.amazonaws.com'
